import { Inter } from "next/font/google";
import "./globals.css";
import Header from '../components/Header/Header';
import { Toaster } from "@/components/ui/sonner";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header/>
        <main className="max-w-7xl mx-auto px-4 py-4">
          <div className="w-full">
            {children}
          </div>
        </main>
        <Toaster />
      </body>
    </html>
  );
}
